gjaldon/heroku-buildpack-phoenix-static

- bin/compile
- lib/build.sh
- phoenix_static_buildpack.config
mix deps.get must be run before npm install so 
that the local deps/phoenix and deps/phoenix_html npm packages are available.
> Update for Phoenix 1.1.2 and Brunch 2.1

- README.md
- bin/release
makes it hard to use any other db, or no db at all
> do not activate postgres addon by default

- README.md
- phoenix_static_buildpack.config
This addresses an issue when trying to compile assets in when using Phoenix 1.1.0.
See https://github.com/phoenixframework/phoenix/issues/1410 for more details.
> Bump node_version to 5.3.0

- lib/build.sh
* Fixes errors like: `cp: ‘/tmp/build_53960f7b097c02e37827c199ce104686/bower.json’ and ‘./bower.json’ are the same file`
* explicitly `cd`s to the necessary directory, so that each `function`'s body is self-descriptive
* avoids using `cd -`, because it makes it harder to know which dir you'll be jumping to (since it depends on the order of execution)
> Fix cp failures

- README.md
- lib/build.sh
- lib/common.sh
- phoenix_static_buildpack.config
Add support for phoenix under umbrella project.
Fixes issue https://github.com/gjaldon/heroku-buildpack-phoenix-static/issues/21
> Add support for umbrella project.

- lib/common.sh
If the MIX_ENV is set through Heroku application config, it should be
used directly and ignore the file based value.
Reference:
https://github.com/HashNuke/heroku-buildpack-elixir/commit/abe76e0c3dc0400234d59d13c6627867079773a5
> Fixed MIX_ENV doesn't change after deployment unless cache is cleared

- lib/build.sh
Apparently npm doesn't actually work sometimes when dependencies change. A prune is required prior to install in certain cases (like upgrading from react-router 2.x to 3.0.0-alpha)
> npm prune before install

- README.md
- compile
Phoenix ships a `package.json` that has a script called `deploy` which
can be used as a generic way to compile your assets during a deploy
instead of using brunch directly.
This change allows an application to change the `deploy` npm script
instead of having to provide a custom compile script.
Here's the template `package.json` Phoenix ships with.
https://github.com/phoenixframework/phoenix/blob/master/installer/templates/static/brunch/package.json
> Replace brunch build with npm deploy script

- README.md
- compile
Reverts gjaldon/heroku-buildpack-phoenix-static#38
- rolling back since this change was backwards-incompatible. will need to deprecate the feature instead.
> Revert "Replace brunch build with npm deploy script"

- bin/compile
- lib/build.sh
This is based heavily on https://github.com/heroku/heroku-buildpack-nodejs/compare/yarn
It appears to work for me. It'll only trigger if there is a `yarn.lock` in the root of the project.
> Add yarn support

- compile
- lib/build.sh
Phoenix 1.3 will introduce `mix phoenix.digest.clean` which allows us to do what the ruby buildpack does and keep our old versions of assets cached and clean them intelligently.
Given that not everyone will upgrade immediately, this will probably need to be an option for the time being.
> Cache static between builds and use phoenix.digest.clean

- phoenix_static_buildpack.config
One issue with the current configuration is Node 5 was never an LTS release, so moving this up to 6.9.2 brings it to LTS and the most applicable support for Phoenix applications.
The other major issue is that this release relies on NPM 2, which has a tiered module management system, causing some unwieldy and memory-intensive node applications. NPM 3 has a flat listing of node modules, which significantly reduces the size of some applications.
I discovered this change after trying to use the latest Babel, and running into issues deploying my application to Heroku. Once I split off of this config and opted for LTS, my application was able to deploy and my application size was down quite a bit.
> Update default Node from 5 to 6 LTS

- lib/build.sh
Previously, the cache would grow and grow even if `mix phoenix.digest.clean` was
deleting files, they wouldn't get deleted in the cache.
> Delete extraneous files when syncing static cache

- README.md
- bin/compile
- compile
- lib/build.sh
- lib/common.sh
- phoenix_static_buildpack.config
Extract for possible configuration changes:
- ```assets_dir``` which for phoenix 1.3 is under ```assets``` instead root
- ```phoenix_ex``` for support of new phoenix mix tasks phoenixframework/phoenix#1927  
One topic to decide is default values for new config variables. For now they are set to match phoenix 1.2.x After official release they should be changed to match current phoenix conventions.
Updates #57
> Add support for phoenix 1.3

- README.md
The compile file example no longer works as is. By linking to the existing compile file, we minimize the chance this example will get outdated, and make it easier to find the current working version. Example of custom compile script updated as well to use expected bash variables.
> Update Readme with current compile file behavior

- lib/build.sh
s3pository is currently down and this is what the official node buildpack uses.
> Use herokai for node

- lib/build.sh
I ran into this error when the priv folder does not exist and the cache is empty. My repo does not have a `priv/` folder and it feels weird for me to create an empty directory just to get this buildpack to work. 
```
rsync: change_dir#3 "/tmp/build//priv" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(712) [Receiver=3.1.0]
```
I was able to reproduce the error by running this manually
```
root@6a03460d0f87:/tmp/build# rsync -a -v --ignore-existing /tmp/cache/phoenix-static/ priv/static
sending incremental file list
rsync: change_dir#3 "/tmp/build//priv" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(712) [Receiver=3.1.0]
```
And the error goes away if I run
``` …
```
> Create priv/ directory if it does not exist.

- README.md
- bin/release
While deploying the app generates the warning
```sh
mix phoenix.server is deprecated. Use phx.server instead.
```
Command must be updated before being discontinued
Multiple projects (all with phoenix version >1.3) were deployed to Heroku using this change
> Update to actual command to start the server

- lib/build.sh
This adds the [--check-files](https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-check-files) option to the `yarn install` command.
This will prevent problems in situations where the node_modules is missing files for some reason.  This could happen if the cached node_modules is bad for some reason.  
I specifically saw this issue happen when trying to use this buildpack on Cloud Foundry, which uploads deployed files from a local directory (as opposed to always checking out from git like Heroku).  I somehow got a bad cache uploaded, and was unable to get a successful build until I added this option to have yarn fill in missing files.  I could have avoided this I think if I'd had node_modules in the .cfignore from the beginning, but I didn't realize until it was too late.  Could have …
> add --check-files option to yarn install

- bin/release
- lib/common.sh
- phoenix_static_buildpack.config
passed `phoenix_ex` var from `lib/common.sh#load_config()` to `bin/release` through a small file generated in $BUILD_DIR.
Calling load_config() from inside `release` caused error, because of the messages echoed from load_config() were considered part of the YAML output generated by the release script.
also changed the logic of load_config(), bc phoenix 1.3.x apps have a package.json on ./assets/, that wasn't detected. and moved the sourcing of `phoenix_static_buildpack.config` at the end to override what was already set from the defaults if the file is present.
> Var in release

- lib/common.sh
I view following a convention, or a default, to be a good thing. When looking through the logs of a deployment, I get concerned with WARNING's. 
I thought this warning was a bit superfluous and misleading.
> No warn for default

- bin/release
- lib/build.sh
- phoenix_static_buildpack.config
Thanks for the amazing work on this buildpack! I ran into a couple issues when setting this up with recent phoenix project:
* Use `--sname` to allow `iex` console sessions to connect to the running process
* Clear out `node_modules`, regardless of node/npm version, when `clean_cache` is enabled
* Use `cp -R` to avoid the build failing if a node module is symlinked. The latest [phoenix package.json](https://github.com/phoenixframework/phoenix/blob/cfb83d9eff1373d44a8d811e77b22beac0f9a42a/installer/templates/phx_assets/package.json#L10-L11) symlinks by default.
> Phoenix 1.4 Upgrade

- lib/build.sh
When `clear_cache` is enabled and the deploy is adding private packages (requiring an `.npmrc` file) the deploy will fail. This is due to the `npm prune` command missing the same `--userconfig` flag.
While I was in there, I integrated `NPM_TOKEN` support to generate an `.npmrc` like other buildpacks on Heroku support out-of-the-box.
I think I can refactor the generation code to use the ENV exports method from common.sh, but was not sure so I went with the safest option.
> Support NPM_TOKEN to .npmrc and fix issue with prune

- lib/common.sh
We frequently encounter issues when there are stray characters such as ^M
> Allow only numbers and dots in versions
